# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{spam_classifier}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["nikola chochkov"]
  s.date = %q{2011-04-29}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{nikola@howkul.info}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "benchmark/benchmark.rb",
    "examples/spam_classifier_url_detection_spec.rb",
    "examples/spammable.rb",
    "lib/spam_classifier.rb",
    "lib/spam_classifier/spam_classifier.rb",
    "spec/base_spec.rb",
    "spec/features_spec.rb",
    "spec/spam_classification_index_spec.rb",
    "spec/spam_classifier_spec.rb",
    "spec/spammable_test.rb",
    "spec/spec_helper.rb",
    "spec/training_examples_spec.rb",
    "spec/words_spec.rb"
  ]
  s.homepage = %q{http://github.com/chochkov/spam_classifier}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "examples/spam_classifier_url_detection_spec.rb",
    "examples/spammable.rb",
    "spec/base_spec.rb",
    "spec/features_spec.rb",
    "spec/spam_classification_index_spec.rb",
    "spec/spam_classifier_spec.rb",
    "spec/spammable_test.rb",
    "spec/spec_helper.rb",
    "spec/training_examples_spec.rb",
    "spec/words_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

